### ISSUE TITLE
Sending Readable Tilt Data

### ISSUE THREAD

**Issue by agg23** [OvermindDL1/EnableRazer#1]
I found your original exploration of handling the scroll wheel tilt events [in this issue](https://github.com/mbuesch/razer/issues/44), and was wondering if you could shed any light on your discovery process. I have become fed up with Razer Synapse on macOS enough to work on building an alternative, and the only thing stopping me is handling tilt events. I was very pleased to find that your Haskell script works unmodified (with the exception of disabling claiming the interface) on macOS, and successfully disables the scrolling tilt functionality. Any insight you might provide is greatly appreciated.

**Comment by OvermindDL1** [comment]
Sadly I did not.  I eventually got extremely irritated with both Razer's lack of software quality and their growing lack of hardware quality that I eventually went to Corsair Keyboards/Mice, of which the build quality is *substantially* better and the open source software is worlds above in capabilities, quality, and stability than any Razer open source software.  I'll accept any PR's here if any are sent (I can still test it with my old razer mouse with the broken left mouse button) but otherwise feel free to fork and take it over.  :-)

But overall, I did not have a Windows VM to test with so I tried lots and lots of random signals unsuccessfully.  The best way to figure it out would be to setup windows in a vm, install the razer drivers, let the VM take over the USB but use USB debugging so you can dump the communicated output between the mouse and the windows drivers.  Then introspecting into that (assuming they are not encrypted, I started worrying about that with razer...) you should be able to find the right magical incantation to make it work.  If only Razer was a good enough company to release the specs on the communication interface...  :-/

If any other questions then feel free to keep asking them in this issue (I'm closing it to keep my list clean ^.^;) and I'll see what I can dredge up from my ancient memories.  :-)
